<?php 
$brands = $this->getBrands();
$helper = $this->helper('Icube\Brands\Helper\Data');
$config = $helper->getConfig();
?>

<div id="brands" class="block block-compare" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">
    <div class="block-title">
        <strong id="block-compare-heading" role="heading" aria-level="2"><?php echo __('Shop By Brand');?>:</strong>
    </div>
    <ul class="items">
    	<?php foreach (range('0', '9') as $char) :?>
	    	<?php if(isset($brands[$char])):?>
	    		<div class="brand-char-sidebar">
	    			<!-- <strong> # <?php echo $char;?></strong> -->
		    		<?php foreach($brands[$char] as $_brand):?>
		    			<li>
			    			<?php if($_brand->getCategoryUrl()):?>
			    				<a href="<?php echo $this->getUrl().$_brand->getCategoryUrl()?>"><?php echo $_brand->getName();?></a>
			    			<?php else:?>
			    				<a href="<?php echo $this->getUrl('catalogsearch/advanced/result/').'?'.$config.'[]='.$_brand->getAttributeId();?>"><?php echo $_brand->getName();?></a>
			    			<?php endif;?>
		    			</li>
		    		<?php endforeach;?>
	    		</div>
	    	<?php endif;?>
	    <?php endforeach;?>
	    <?php foreach (range('A', 'Z') as $char) :?>
	    	<?php if(isset($brands[$char])):?>
	    		<div class="brand-char-sidebar">
	    			<!-- <strong> # <?php echo $char;?></strong> -->
	    			<?php foreach($brands[$char] as $_brand):?>
	    				<li>
	    					<?php if($_brand->getCategoryUrl()):?>
	    						<a href="<?php echo $this->getUrl().$_brand->getCategoryUrl()?>"><?php echo $_brand->getName();?></a>
	    					<?php else:?>
	    						<a href="<?php echo $this->getUrl('catalogsearch/advanced/result/').'?'.$config.'[]='.$_brand->getAttributeId();?>"><?php echo $_brand->getName();?></a>
	    					<?php endif;?>
    					</li>
    				<?php endforeach;?>
				</div>
			<?php endif;?>
		<?php endforeach;?>
	</ul>
</div>
